FROM ubuntu:18.04

# At the moment, setting "LANG=C" on a Linux system *fundamentally breaks Python 3*, and that's not OK.
ENV LANG C.UTF-8

ENV PYTHONUNBUFFERED 1

# Install Python OS dependencies
RUN apt-get update && apt-get install -y --no-install-recommends \
        python3-dev \
        python3-pip \
        python3-setuptools \
        locales \
        tzdata \ 
        gcc \
        python-psycopg2
