FROM ubuntu-python3:latest

# Requirements have to be pulled and installed here, otherwise caching won't work
COPY ./requirements /requirements

# Setup locales
RUN echo "en_US.UTF-8 UTF-8" > /etc/locale.gen \
    && locale-gen

# Setup timezone
ENV TZ=Asia/Bangkok
RUN echo "Asia/Bangkok" > /etc/timezone && \
    rm /etc/localtime && \
    ln -snf /usr/share/zoneinfo/$TZ /etc/localtime && \
    dpkg-reconfigure -f noninteractive tzdata

# Upgrade PIP to latest version
RUN pip3 install --upgrade pip
RUN pip3 install -r /requirements/base.txt

WORKDIR /app
